name: Deploy and Release

on:
  push:
    branches:
      - main

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install && bun run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g semantic-release @semantic-release/exec
      - run: |
          semantic-release \
            --plugins @semantic-release/exec \
            --exec-publish "cp dist/index.html release.html && gh release upload $GITHUB_REF_NAME release.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

